##
# .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'rails'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true


##
# ./spec/.rubocop.yml

inherit_from:
  - ../.rubocop.yml

StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - './*_helper.rb'

# describe block
Metrics/BlockLength:
  Enabled: false


##
# ./spec/fabricators/.rubocop.yml

inherit_from:
  - ../../.rubocop.yml


##
# ./spec/support/.rubocop.yml

inherit_from:
  - ../../.rubocop.yml

  
