require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.3
  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

  Exclude:
    - 'app/views/**/*'
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'scripts/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'

Documentation:
  Enabled: false

IndentationConsistency:
  EnforcedStyle: 'rails'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails:
  Enabled: true

StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - './*_helper.rb'

# describe block
Metrics/BlockLength:
  Enabled: false
